# LOG
#
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETCHAR=y
CONFIG_CONSOLE_GETCHAR_BUFSIZE=64
CONFIG_CONSOLE_PUTCHAR_BUFSIZE=512

CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_DEFAULT_LEVEL=3


CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_I2S=y
CONFIG_SPI=y
CONFIG_INPUT=y

CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_DSP_TRANSFORM=y
CONFIG_REQUIRES_FULL_LIBC=y

CONFIG_MAIN_STACK_SIZE=8192


# SDCARD 
#
CONFIG_SDHC=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_SD_DATA_TIMEOUT=100
CONFIG_SD_RETRY_COUNT=5


# FILE SYSTEM
#
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_LFN_MODE_STACK=y
CONFIG_FS_FATFS_REENTRANT=y


# AUDIO
#
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y


# USB CDC
#
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_UART_LINE_CTRL=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y
CONFIG_USBD_LOG_LEVEL_WRN=n
CONFIG_USBD_LOG_LEVEL_ERR=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=n
CONFIG_UDC_DRIVER_LOG_LEVEL_ERR=y


# WS2812
#
CONFIG_SPI=y
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y



# BLUETOOTH 
#
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_SCAN=y
CONFIG_BT_SCAN_FILTER_ENABLE=y
CONFIG_BT_SCAN_UUID_CNT=5
CONFIG_BT_SCAN_NAME_CNT=5
CONFIG_BT_SCAN_APPEARANCE_CNT=5
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=5
CONFIG_BT_FILTER_ACCEPT_LIST=y


# [보안 및 본딩 핵심 엔지니어링]
CONFIG_BT_SMP=y
CONFIG_BT_BONDABLE=y
CONFIG_BT_L2CAP_DYNAMIC_CHANNEL=y


# 패드의 임의/가상 주소(RPA) 매칭을 위해 필수 활성화
CONFIG_BT_PRIVACY=y
CONFIG_BT_RPA_TIMEOUT=900


# 링크 레이어 하드웨어 레벨에서 페어링된 주소를 즉시 판별하도록 캐시 할당
CONFIG_BT_CTLR_RPA_CACHE_SIZE=4


# [GATT 및 버퍼 최적화]
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_GATT_DM=y
CONFIG_BT_GATT_AUTO_DISCOVER_CCC=y
CONFIG_BT_ATT_PREPARE_COUNT=5
CONFIG_BT_RX_STACK_SIZE=8192
CONFIG_BT_CTLR_CRYPTO=y


# [시스템 워크큐 및 스레드]
CONFIG_THREAD_NAME=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192


# SETTINGS & FLASH BACKEND (페어링 정보 영구 저장)
# 
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_NVS=y

CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_BT_SETTINGS=y


# 재연결 시 기존 CCCD(구독 정보)를 플래시에서 안정적으로 지연 로드
CONFIG_BT_SETTINGS_CCC_LAZY_LOADING=y


# DEBUG LOG LEVEL
# 
CONFIG_BT_LOG_LEVEL_INF=y
CONFIG_BT_SCAN_LOG_LEVEL_INF=y
CONFIG_SETTINGS_LOG_LEVEL_DBG=y


# GATT 및 MTU 최적화 (협상 단계를 줄여 속도 향상)
CONFIG_BT_L2CAP_TX_MTU=65
CONFIG_BT_BUF_ACL_RX_SIZE=69
CONFIG_BT_BUF_ACL_TX_SIZE=69

# Data Length Extension 활성화 (패킷 한 번에 많이 보내기)
CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=69

# 연결 파라미터 자동 업데이트 타임아웃 단축
CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT=5000

# CONFIG_BT_CONN_PARAM_UPDATE=y
# CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=y